### ISSUE TITLE
【BUG】: adpE使用的阈值没有限制小于1

### ISSUE THREAD

**Issue by lartpang** [DengPingFan/CODToolbox#2]
https://github.com/DengPingFan/CODToolbox/blob/910358910c7824a4237b0ea689ac9d19d1958d11/Onekey_Evaluation_Code/OnekeyEvaluationCode/main.m#L88-L93

建议直接将：

```matlab
            threshold =  2* mean(sal(:)) ;
```

替换为：

```matlab
            threshold = min(2 * mean2(sal), 1);
```

**Comment by DengPingFan** [comment]
> https://github.com/DengPingFan/CODToolbox/blob/910358910c7824a4237b0ea689ac9d19d1958d11/Onekey_Evaluation_Code/OnekeyEvaluationCode/main.m#L88-L93
> 
> 建议直接将：
> 
> ```matlab
>             threshold =  2* mean(sal(:)) ;
> ```
> 
> 替换为：
> 
> ```matlab
>             threshold = min(2 * mean2(sal), 1);
> ```

这里确实应该限制一下小于等于1. 非常感谢你指出这个错误。还好平时的时候大家没有怎么用adpE-m。 这样的情况也是偶然发生。我已经修复了这个bug了。
